project_id = "vvklvjxfbjdgsnmubrhh"

[functions.send-order-confirmation]
verify_jwt = false

[functions.notify-admin-new-order]
verify_jwt = false

[functions.scrape-product-url]
verify_jwt = false

[functions.supplier-api]
verify_jwt = false
